# Generated by Django 5.2.11 on 2026-02-24 04:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_group_year"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="group",
            unique_together={("school", "year", "group")},
        ),
    ]
