# Generated by Django 5.2.11 on 2026-02-24 04:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_group_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="group",
            unique_together={("year", "group")},
        ),
    ]
