# Generated by Django 5.2.11 on 2026-02-24 04:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_group_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="group",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="group",
            name="year",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(11),
                ]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="group",
            unique_together={("school", "year", "group")},
        ),
    ]
